services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /path/to/videos
        target: /Videos
        read_only: true
      - type: bind
        source: /path/to/music
        target: /Music
        read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    ports:
      - 8096:8096
